DATA:
  DEN_ROOT: 'datasets/den/'
  GDEN_ROOT: 'datasets/gden/'
  SLIC_SEGMENTS: 1000
  SLIC_COMPACTNESS: 0.1
  TRAIN_SUBSET: 'train'
  VAL_SUBSET: 'val'
  TEST_SUBSET: 'test'
  NUM_WORKERS: 1
  CLASSES: [0,1,2,3,4,5,6]
TRAINING:
  EPOCHS: 10000
  EARLY_STOPPING: 500
  BATCH_SIZE: 4
  LR: 0.0001
EVALUATION:
  BATCH_SIZE: 1
NETWORK:
  NAME: 'gcn'
  INPUT_CHANNELS: 16
  OUTPUT_CHANNELS: 6
  WIDTHS: [256,256,256,256]
  NORM: 'batch'
LOSS:
  TYPE: 'focal-loss'
  IGNORE_INDEX: 6

