DATA:
  DEN_ROOT: 'datasets/den/'
  GDEN_ROOT: 'datasets/gden/'
  SLIC_SEGMENTS: 1000
  SLIC_COMPACTNESS: 0.1
  TRAIN_SUBSET: 'train'
  VAL_SUBSET: 'val'
  TEST_SUBSET: 'test'
  NUM_WORKERS: 1
  CLASSES: [0,1,2,3,4,5,6]
NETWORK:
  NAME: 'rf'
  N_TREES: 100
  MAX_DEPTH: 20
  INPUT_CHANNELS: 16
  OUTPUT_CHANNELS: 6
LOSS:
  IGNORE_INDEX: 6

